apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rp56zjpbx-go 
  janus-idp.io/tekton: rp56zjpbx-go
  backstage.io/kubernetes-id: rp56zjpbx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rp56zjpbx-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  